# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('year', models.DateField()),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_info_received', models.BooleanField(default=False)),
                ('full_info_json', models.TextField(default='')),
                ('dvd_release_date_status', models.CharField(choices=[('NA', 'N/A'), ('NF', 'not received'), ('NP', "couldn't parse"), ('R', 'valid date received')], default='NF', max_length=2)),
                ('dvd_release_date', models.DateField(default=django.utils.timezone.now)),
                ('raw_dvd_release_date', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
