# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvd_release_date', models.DateField()),
                ('dvd_release_date_status', models.CharField(choices=[('NA', 'N/A'), ('NF', 'not found'), ('R', 'received')], max_length=2)),
                ('is_info_received', models.BooleanField()),
                ('full_info_json', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
