# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='info',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='movies.MovieInfo'),
            preserve_default=False,
        ),
    ]
