# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20170409_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='info',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
            preserve_default=False,
        ),
    ]
