# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170409_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieInfo',
        ),
    ]
