# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20170409_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='dvd_release_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 9, 12, 11, 57, 422758, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='movie',
            name='dvd_release_date_status',
            field=models.CharField(choices=[('NA', 'N/A'), ('NF', 'not found'), ('R', 'received')], default='NF', max_length=2),
        ),
        migrations.AddField(
            model_name='movie',
            name='full_info_json',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_info_received',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MovieInfo',
        ),
    ]
