# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20170409_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dvd_release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 9, 12, 12, 50, 152265, tzinfo=utc)),
        ),
    ]
