# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20170409_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 9, 18, 1, 54, 8035, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='dvd_release_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 9, 18, 1, 54, 8035, tzinfo=utc)),
        ),
    ]
