# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20170409_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dvd_release_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 16, 7, 20, 788941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 16, 16, 7, 20, 788941, tzinfo=utc)),
        ),
    ]
