# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20170722_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmdbMovie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='TMDB id')),
                ('update_date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('us_digital_release_date', models.DateField(blank=True, null=True)),
                ('us_physical_release_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=1024)),
                ('overview', models.TextField(blank=True)),
                ('runtime', models.IntegerField(default=-1)),
                ('imdb_id', models.CharField(default='', max_length=32, verbose_name='iMDB id')),
            ],
        ),
        migrations.RenameModel(
            old_name='Movie',
            new_name='OmdbMovie',
        ),
    ]
