# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20170723_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdbmovie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='iMDB id'),
        ),
        migrations.AlterField(
            model_name='tmdbmovie',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmdbmovie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmdbmovie',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tmdbmovie',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
