# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20170723_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdbmovie',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
