# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20170726_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OmdbMovie',
        ),
        migrations.RenameField(
            model_name='tmdbmovie',
            old_name='update_date',
            new_name='update_time',
        ),
    ]
